// Generated by https://quicktype.io

export interface LocationsResponse {
  info:    InfoLocations;
  results: Location[];
}

export interface InfoLocations {
  count: number;
  pages: number;
  next:  string;
  prev:  null;
}

export interface Location {
  id:        number;
  name:      string;
  type:      string;
  dimension: string;
  residents: string[];
  url:       string;
  created:   string;
}
